### ISSUE TITLE
Add function not working properly

### ISSUE THREAD

**Issue by devndive** [devndive/exploring-github#1]
The add function is not working. It seems like it always adds the first number passed to the function to itself. I am wondering if someone can spot the issue and provide a pull request to fix that.

This is a good first issue. If you have not provided a pull request to someones repository try these steps:

- Fork the repository you want to provide a fix to
- Clone your fork to your local computer
- Make the changes you think are necessary
- Commit your changes
- Push your changes to your fork
- [Create a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

When creating the pull request add a comment like `fixing devndive/exploring-github#1`

Once you have made the pull request I will review and merge it.

**Comment by sreekeshiyer** [comment]
#2 

Done. 

Thank you @devndive for doing this!
I'm very new to Open Source, I've been working on web dev and coding for the last few years but never felt confident enough to contribute to Open Source Projects and I was looking for `good first issue`s today. 

I'm hoping this gives me a good headstart. Good day :)

**Comment by devndive** [comment]
PR #3 fixed this issue
